## YAML Template.
language: java
addons:
    sonarcloud:
        organization: ninojairo-github
        token:
            secure: "gVfHnkwdeCcKZ9q5kOhRZWtepoAQ2AVJIISk8F+wpvJFV1oZRykvAVbmBcmUEQXy5pRtV2B7q9/Z04rA3+06CEMpbznt7AGhHFFmnUXaPz+qhh1niT6sZgMKplcShtRNu2G7A3soMbrW5KF9Oivj8002SYyUXlsiA6mzxsPmCAcIJ9Oc5fnkuR7fy/V+LRexw4UzLcVohdvmdua4v9knc3KW6xoFJOQJ/z6Dd+V0qpzCh2WHtKtaE2EBEgVuCwK2QFiEaTw9xWacTNJ/rhGY147DfmhtyqdTF7CvJd0RJhT5+KbUVBXde8xN0bJCEjSdAtq5DoMuei500BeYjJV8jbPB5T9/NPkCIDAhvXWsdgFQGLrdRcfgnks0RbFq9zWXOs2K8t+7V4lrl4bnHVt8/sCZZDQKpNtKAxv3F33OpFwbH5sM2FvgUq9bTKCoP0jRgzvvgJkpZ4Twnhg44sh21LYM+zBqm7xwxSvHt4L4Zw6eXnGEpcNb0hKyYePiphJlYSZKA7aHZFOEFnpH7eD92WMuW9qvWW5440yTwCiTqhd0G1srnIE3hpe0YXx2awezOgcXyLYlZFfxOEAU9YalEL8ZKsRrAYZN2TCpVts+iOs7oApA0o2MrldpgI4+D7bhwXsHEkAGYHzvae+cShzNgnS41kVATUV9PNk2jIdSPUY="
script: 
    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
---
