## YAML Template.
language: java
addons:
    sonarcloud:
        organization: "ninojairo-github"
        token:
            secure: eFetloRpWGrP9bkBmG5ECm7weRg+NdC5IB/x1Jfcvv6bGjEbds+VyzIH1yryRZ2bsoc0kHfW+xSSJEtz+tR/FapO9U+mWS33DR+G/raacKHUxAsO4vC48wk5JrYKAl3FjcIFHEZIOVSHT58RJaDNry62WrJ6k7olwt1gwBK0RN3Tnb3PZIFllAlPyL+n3BStlB4Sn0Gs3SRylnWI5m1UnLoSI6HOigY3vxMrU21gOWcG3/xVtXdQozDEVtC1vHMArPqmjqiS5d648AvowgF4jIDX5toveiDfukaNfipI3mmOdZQl/S7uUiA3FYL3YOKY4pa3xNt0KN7miTV6owCDAAjoVEhCvbjFVIwDhEdz0tzoe7ZIyO1LYQu+KgEbVQt7le7aga6hqfC8/VN9uRCsQv///kVbB7xwpqEN8ICE2EcUiUdQIaHjJ/9A3NizVroWcsjX9H8qhKXat0jTcTxYloFwa0SNSOWqx1Xq1BtrHGsH7GZBvMzFEOtRWKvioj0duLOTzWp1FBmM1tWmoDEhlJxn+R2uQ31qZrs51pXBTJmRDEB6MEWDZyzuestVAKpCc0XmfBVuYZLbZWDqAxY0w1hPL0HmznbQmFwS/8HDUpLnxMUL6p7COya1KrUcBlkS3LgGRIZiLgLIfJs3rVit9r2J0Iry4QgSDEDdutXh5hc=
script: 
    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
---
